### Fetch Browser Monitoring Pinned Version
POST https://api.newrelic.com/graphql
Content-Type: application/json
API-Key: {{apiKey}}

{
  "query": "query FetchBrowserMonitoringAgentSettings($browserMonitorGuid: EntityGuid!) { actor { entity(guid: $browserMonitorGuid) { ... on BrowserApplicationEntity { guid name browserSettings { browserMonitoring { loader pinnedVersion } } } } } }",
  "variables": {
    "browserMonitorGuid": "{{browserMonitorGuid}}"
  }
}

### Set Browser Monitoring Pinned Version
POST https://api.newrelic.com/graphql
Content-Type: application/json
API-Key: {{apiKey}}

{
  "query": "mutation SetBrowserMonitoringPinnedVersion($browserMonitorGuid: EntityGuid!, $pinnedVersion: String!) { agentApplicationSettingsUpdate(guid: $browserMonitorGuid, settings: { browserMonitoring: { pinnedVersion: $pinnedVersion } }) { browserProperties { jsLoaderScript } browserSettings { browserMonitoring { loader pinnedVersion } } } }",
  "variables": {
    "browserMonitorGuid": "{{browserMonitorGuid}}",
    "pinnedVersion": "1.260.0"
  }
}

### Clear Browser Monitoring Pinned Version
POST https://api.newrelic.com/graphql
Content-Type: application/json
API-Key: {{apiKey}}

{
  "query": "mutation ClearBrowserMonitoringPinnedVersion($browserMonitorGuid: EntityGuid!) { agentApplicationSettingsUpdate(guid: $browserMonitorGuid, settings: { browserMonitoring: { pinnedVersion: null } }) { browserProperties { jsLoaderScript } browserSettings { browserMonitoring { loader pinnedVersion } } } }",
  "variables": {
    "browserMonitorGuid": "{{browserMonitorGuid}}"
  }
}
